version: "3.9"

services:
  evoting:
    build: .
    container_name: evoting_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./static/uploads:/app/static/uploads
    restart: always
